ALTER TABLE paciente_fila_espera MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE paciente_fila_normal MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE paciente_fila_urgente MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE paciente_fila_preferencial MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE historico_senhas_chamadas MODIFY COLUMN id BIGINT AUTO_INCREMENT;
